### ISSUE TITLE
Favicon is invisible on a grey background

### ISSUE THREAD

**Issue by RX14** [octobox/octobox#1157]
The standard dark theme of firefox has exactly the same background colour as the foreground colour of the favicon, rendering the icon invisible unless hovered over.

![](http://owo.sh/f4af75.png)

![](http://owo.sh/eb7886.png)

**Comment by BenJam** [comment]
Errr... is there any way to detect whether the browser is running in dark mode so we can render a light one?

**Comment by RX14** [comment]
I don't think there is. Most sites use some kind of background or border on their logo to avoid this.

**Comment by andrew** [comment]
Maybe we can just make it pure black, like the GitHub logo?

**Comment by RX14** [comment]
The github logo also looks pretty bad on a dark background. But not invisible.

![](http://owo.sh/810245.png)

**Comment by ahmadnassri** [comment]
> Source: StackOverflow [Q:50840168](https://stackoverflow.com/questions/50840168/how-to-detect-if-os-x-is-in-dark-mode-in-browsers)

New standard is registered on W3C in [Media Queries Level 5](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme).

NOTE: currently only available in [Safari Technology Preview Release 68](https://developer.apple.com/safari/technology-preview/release-notes/)

In case user preference is light:

```css
/* Light mode */
@media (prefers-color-scheme: light) {
    body {
        background-color: #000;
        color: white;
    }
}
```

In case user preference is dark:

```css
/* Dark mode */
@media (prefers-color-scheme: dark) {
    body {
        background-color: #000;
        color: white;
    }
}
```
There is also the option no-preference in case a user has no preference. But I recommend you just to use normal css in that case and cascade your CSS correctly.
