### ISSUE TITLE
ArgumentError in NotificationsController#sync: invalid uri scheme ''

### ISSUE THREAD

**Issue by davidcelis** [octobox/octobox#1501]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

I recently updated Octobox for the first time after several months, and something having to do with ActionCable is breaking notification syncing for me. When attempting to sync, I get the following error:

```
Completed 500 Internal Server Error in 801ms (ActiveRecord: 10.0ms | SQL count: 25)

ArgumentError (invalid uri scheme ''):
  
app/models/notification.rb:190:in `push_to_channel'
app/models/subject.rb:132:in `push_to_channels'
app/models/subject.rb:60:in `sync'
lib/octobox/notifications/sync_subject.rb:25:in `update_subject_in_foreground'
app/workers/update_subject_worker.rb:8:in `perform'
config/initializers/custom_sidekiq_worker.rb:9:in `perform_async_if_configured'
lib/octobox/notifications/sync_subject.rb:14:in `update_subject'
app/models/notification.rb:151:in `update_from_api_response'
app/services/download_service.rb:58:in `block in process_notifications'
app/services/download_service.rb:53:in `each'
app/services/download_service.rb:53:in `process_notifications'
app/services/download_service.rb:46:in `fetch_new_notifications'
app/services/download_service.rb:26:in `download'
app/models/user.rb:80:in `sync_notifications_in_foreground'
app/controllers/notifications_controller.rb:249:in `sync'
```

And this is the extracted source:

```ruby
def push_to_channel
    string = ApplicationController.render(partial: 'notifications/notification', locals: { notification: self})
    ActionCable.server.broadcast "notifications:#{user_id}", { id: "#notification-#{id}", html: string }
  end

  def update_repository(api_response)
```

The `ActionCable.server.broadcast` line is the one raising the error.

Also note, this is essentially a fresh Octobox. I experienced something weird with Octobox not using my PAT to fetch notifications from private repos, so I ended up deleting my data volumes and attempting to start from scratch. So for all intents and purposes, this is a fresh Octobox installation.

🎯 **Goal**

Notifications should be able to sync.

🔧 **Configuration**

This is how I've configured my Octobox instance:

```sh
RAILS_ENV=development
GITHUB_CLIENT_ID=<snip>
GITHUB_CLIENT_SECRET=<snip>
OCTOBOX_DATABASE_NAME=postgres
OCTOBOX_DATABASE_USERNAME=postgres
OCTOBOX_DATABASE_PASSWORD=<snip>
OCTOBOX_DATABASE_HOST=database.service.octobox.internal
REDIS_URL=redis.service.octobox.internal
MINIMUM_REFRESH_INTERVAL=1
PERSONAL_ACCESS_TOKENS_ENABLED=1
RESTRICTED_ACCESS_ENABLED=1
GITHUB_ORGANIZATION_ID=<snip>
GITHUB_SCOPE=notifications,read:org,repo
FETCH_SUBJECT=true
ADMIN_GITHUB_IDS=<snip>
PUSH_NOTIFICATIONS=true
INCLUDE_COMMENTS=true
WEBSOCKET_ALLOWED_ORIGINS=https://my.octobox.url
```

For my own account, I've set a personal access token for Octobox to use instead of the oauth token generated via the OAuth App. I've also set Octobox to open notifications in Octobox itself (using live updates), though this doesn't work due to the inability to fetch subjects.

When I reboot Octobox, several notifications do sync, but not their subjects. This makes sense, as the error appears to occur during fetching subjects and causes a `ROLLBACK` of whatever database transaction is attempting to save them.

**Comment by andrew** [comment]
Are you running it inside of docker or on heroku or locally?

**Comment by davidcelis** [comment]
I've got it running via `docker-compose`:

```yaml
version: '3'
services:
  database.service.octobox.internal:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=<snip>
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  redis.service.octobox.internal:
    image: redis:3.2-alpine
    networks:
      - internal
  app:
    image: octoboxio/octobox:latest
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - GITHUB_CLIENT_ID=<snip>
      - GITHUB_CLIENT_SECRET=<snip>
      - OCTOBOX_DATABASE_NAME=postgres
      - OCTOBOX_DATABASE_USERNAME=postgres
      - OCTOBOX_DATABASE_PASSWORD=<snip>
      - OCTOBOX_DATABASE_HOST=database.service.octobox.internal
      - REDIS_URL=redis.service.octobox.internal
      - MINIMUM_REFRESH_INTERVAL=1
      - PERSONAL_ACCESS_TOKENS_ENABLED=1
      - RESTRICTED_ACCESS_ENABLED=1
      - GITHUB_ORGANIZATION_ID=<snip>
      - GITHUB_SCOPE=notifications,read:org,repo
      - FETCH_SUBJECT=true
      - ADMIN_GITHUB_IDS=<snip>
      - PUSH_NOTIFICATIONS=true
      - INCLUDE_COMMENTS=true
      - WEBSOCKET_ALLOWED_ORIGINS=https://<snip>
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
```
