### ISSUE TITLE
Formatting issues after upgrading bootstrap

### ISSUE THREAD

**Issue by RX14** [octobox/octobox#726]
Before:

![](http://owo.sh/d13f0c.png)

After:

![](http://owo.sh/b50c70.png)

The sidebar looks great, but the rest of the page seems to have been inflated to gigantic proportions.

I can fix it by adding `font-size: 14px` to the `:root`, but the text in the table header is then too small:

![](http://owo.sh/c89e96.png)

This can be reproduced by changing the default font size in your browser settings to 20px.

**Comment by pradyunsg** [comment]
This is mostly just an artifact of the default table element padding increasing.

One fix would be:

```css
.table-notifications td { /* or .table td */
    padding: 0.5rem;
}
```
