### ISSUE TITLE
Advanced search query syntax

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#742]
Example:

`unread:true type:issue reason:mention owner:octobox repo:octobox/octobox label:bug free text`

Potential ruby gems we can use for parsing: https://github.com/marcelocf/searrrch

Other potential filters we can support:

- author
- assignee
- subject
- body (#709)
- comments (#709)
- date
- inbox/archive/starred
- team

This is also the first step in enabling custom filters, where if a notification comes in an matches a custom saved search then perform some action, useful for #8, #217 and #599

**Comment by andrew** [comment]
We can also build a drop-down advanced search UI similar to gmails which constructs the query and aids in discover of available filters:

![screen shot 2018-08-06 at 15 30 38](https://user-images.githubusercontent.com/1060/43722698-c9a8bd3c-998d-11e8-8c3e-aa9f2b46ed0e.png)

**Comment by andrew** [comment]
Another follow up will be allowing users to "pin" search queries to the sidebar for easy access (and counts)

**Comment by pradyunsg** [comment]
Ideas for the search bar:

- Use it to replace the filters bar.

- Visually aligning the search bar with the actual table (again, idea from Gmail; done on Octobox by injecting a CSS rule)
  <img width="403" alt="screen shot 2018-08-16 at 3 25 19 pm" src="https://user-images.githubusercontent.com/3275593/44202076-9ef00180-a168-11e8-8472-5dca7d49966d.png">
  ```css
  /* Horrible Hack for aligning search */
  #search {
    position: absolute;
    left: 250px;
  }
  .navbar-brand svg.octobox-icon {
    position: absolute;
    top: 1rem;
    left: 7.5rem;
  }
  ```

- Keep history of searches in the LocalStorage of the user and allow them to remove them (GitLab does something like this IIRC, even Gmail)

**Comment by andrew** [comment]
We should definitely pop the search history item out into it's own issue, I've been meaning to jot that down somewhere.

I also like the idea of bumping the search box across so it aligns with the notifications table, at least on large screens.

**Comment by andrew** [comment]
Copying more elements of the gmail UI just for fun, almost completely unusable but looks nice: 
![screen shot 2018-08-16 at 12 05 02](https://user-images.githubusercontent.com/1060/44204975-b8835000-a14c-11e8-8ab9-c950d40bd737.png)

**Comment by pradyunsg** [comment]
> Copying more elements of the gmail UI just for fun, almost completely unusable but looks nice:

I honestly would like to be able this, now that we have #775 merged.

**Comment by pradyunsg** [comment]
> Visually aligning the search bar with the actual table

Another, slightly less hacky way:

```css
.navbar-brand {
    width: 217px;
    text-align: center;
}
```
