### ISSUE TITLE
Improve visual spacing between checkbox and star in a notification row

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#801]
Before/After
<img width="132" alt="screen shot 2018-08-17 at 10 40 40 am" src="https://user-images.githubusercontent.com/3275593/44248750-0c07a380-a20a-11e8-8f06-c2169ec5b7d3.png"><img width="128" alt="screen shot 2018-08-17 at 10 40 31 am" src="https://user-images.githubusercontent.com/3275593/44248752-0d38d080-a20a-11e8-8e63-e3c0c85888be.png">

The spacing between elements is more consistent with this change. Someone would need to verify how this looks on Linux/Windows though.

```css
.select-all {
    padding-left: 6px;
}
.notification-checkbox input {
    margin-left: 6px;
    margin-right: 0;
}
```

PS: This feels so much better. 😄
